# Generated by Django 5.0.6 on 2024-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='USERNAME_FIELD',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
