# Generated by Django 5.0.6 on 2024-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customer_username_field_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='USERNAME_FIELD',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
