# Generated by Django 5.0.6 on 2024-05-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_user_customer_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='USERNAME_FIELD',
        ),
    ]
